### ISSUE TITLE
Unable to find any test cases

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed-example-typeorm#5]
HI Team,
  Can we have some sample unit/integration test cases to test with mock data. Basically, I am using SQL Server while running the app and need to mock my repositories for Integration Testing / Controller testing via supertest (mocha+chai). Everytime I am getting a 500 in my test case, no matter which API i am going to hit. 
Please if we can add some Unit test cases via supertest that would be great.

**Comment by Romakita** [comment]
Yep I can try :) There is a specific file in this example, you want to have an integration test ?

**Comment by panbhatt** [comment]
Yes, there is a file Calendar.spec.ts under packages/server/test/integration/controllers/calendars. Please if we can make this work that would be great.

**Comment by Romakita** [comment]
Ok I'll add more and complete integration test ;)

**Comment by Romakita** [comment]
But in this repository. There is no packages/server/test/integration/controllers/calendars.

**Comment by panbhatt** [comment]
Please check this. https://github.com/panbhatt/tsed-example-react/blob/v5.57.2-1/packages/server/test/integration/controllers/calendars/Calendars.spec.ts

**Comment by Romakita** [comment]
Yes this is not the same repository. You've opened this issue on https://github.com/TypedProject/tsed-example-typeorm. Isn't easy form to follow you XD

**Comment by Romakita** [comment]
Instead of add integration test on the react example, I prefer to add example the dedicated Typeorm example repository.

The example is ready. See: https://github.com/TypedProject/tsed/blob/production/examples/typeorm/src/controllers/passport/PassportCtrl.integration.spec.ts

Note: All source code examples are hosted on the https://github.com/TypedProject/tsed . Then a job deploy all code on each dedicated repository. Making PR on https://github.com/TypedProject/tsed-example-typeorm for example isn't practical for me because, I have to copy all change to  https://github.com/TypedProject/tsed  XD.

See you
Romain

**Comment by panbhatt** [comment]
Thanks for this example. however the original questions remains so, as we are not mocking the Repository here, but trying to bootstrap typeorm with sqllite (in my case, we can't do sqllite as we are running on node 10.16 and can't install sqllite3 there). 
Isn't there is a way from SINON to mock the repository and its functions.

**Comment by Romakita** [comment]
Probably yes. but this question must be addressed to TypeORM project not to me :)

**Comment by panbhatt** [comment]
I think i fixed this. This can be done by using Jest.fn() or sinon.fake
basically we need to do this. 

import * as typeorm from 'typeorm';

(typeorm as any).getCustomRepository = sinon.fake.returns({}) // in JESt it would be jest.fn().mockreturns({})

in line 2 i can override the functions and it works fine after this. I am using Provider in TYpeorm to inject my repo to service level.

**Comment by Romakita** [comment]
Yes this is probably the right approach :)

**Comment by panbhatt** [comment]
Thanks for the validation. i hope it would be helpful for others.
